metadata:
  name: HF_SM_3
apiVersion: v1
kind: Pod
spec:
  nodeName: host3
  containers:
  - image: ubuntu
    name: containerHF_SM_30
    resources:
      limits:
        memory: 20000.0
        cpu: 1
