# ----------------------------------- Spring Setting --------------------------------------
spring:
  application:
  name: container
# ----------------------------------- Server Setting ------------------------------
server:
  port: 8081
